services:
  db:
    image: mysql:8.0
    container_name: lucee-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: luceeapp
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "3306:3306"

  lucee:
    image: lucee/lucee
    container_name: lucee-app
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "1988:8888"
    volumes:
      - ./src:/var/www/

volumes:
  db_data:
